# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list
  build:
    vars:
      USE_DIR: '{{.DIR | default "$PWD" }}'
    desc: Build the ducktape binary
    cmds:
      - go build -v -o=dist/dt .
    generates:
      - dist/dt
    sources:
      - ./**/*.go
